app/app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth import views

urlpatterns = [
    path('movie/', include('movie.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/movie/urls.py
from django.urls import path
from django.conf.urls.static import static

from . import views

app_name = 'movie'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('upload', views.model_form_upload, name='upload'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('<int:pk>/',views.DetailView.as_view(),name='detail'),
    path('<int:pk>/remove',views.DeleteView.as_view(),name='remove'),
    path('<int:pk>/comment/',views.add_comment,name='add_comment'),
    path('<int:pk>/comment/approve/',views.comment_approve,name='comment_approve'),
    path('<int:pk>/comment/remove/',views.comment_remove,name='comment_remove'),
    path('login/',views.Login.as_view(),name='login'),
    path('logout/',views.Logout.as_view(),name='logout'),
    path('signup/',views.signup,name='signup'),
    path('user/<str:username>',views.UserView.as_view(),name='user'),
    path('<int:pk>/like',views.like_document,name='like_document'),
]

app/movie/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager

# Create your models here.
class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,related_name='user')
    username = models.CharField(max_length=50,default='ken')
    follower = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name='follower',blank=True)

    def __str__(self):
        return self.description

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

class Comment(models.Model):
    post = models.ForeignKey('movie.Document', on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

class CustomUser(AbstractBaseUser, PermissionsMixin):
    user_vali = UnicodeUsernameValidator()
    username = models.CharField(_('username'), max_length=150, unique=True, validators=[user_vali])
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(_('staff status'), default=False)
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    like_document = models.ManyToManyField(Document, verbose_name='Like', blank=True,related_name='like_document')

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

app/movie/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
#from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Document,Comment,CustomUser

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('description', 'document',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  

class SignupForm(UserCreationForm):

    last_name = forms.CharField(
        max_length=30,
        required=False,
        help_text='オプション',
        label='苗字'
    )
    first_name = forms.CharField(
        max_length=30,
        required=False,
        help_text='オプション',
        label='名前'
    )
    email = forms.EmailField(
        max_length=254,
        help_text='必須 有効なメールアドレスを入力してください。',
        label='Eメールアドレス'
    )

    class Meta:
        model = CustomUser
        fields = ('username', 'last_name', 'first_name',  'email', 'password1', 'password2', )

app/movie/views.py
from django.shortcuts import render, redirect, get_object_or_404,HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q

from .models import Document, Comment, CustomUser
from .forms import DocumentForm, CommentForm, LoginForm, SignupForm

class IndexView(generic.ListView):
    template_name = 'movie/index.html'
    context_object_name = 'latest_file_list'

    def get_queryset(self):
        q_word = self.request.GET.get('query')
 
        if q_word:
            object_list = Document.objects.filter(
                Q(description__icontains=q_word) | Q(username__icontains=q_word)).order_by('-uploaded_at')
        else:
            object_list = Document.objects.order_by('-uploaded_at')
        return object_list

class UserView(generic.ListView):
    template_name = 'movie/user.html'
    context_object_name = 'latest_file_list'

    def get_queryset(self):
        username = self.request.path_info.split('/')[-1]
        user_id = CustomUser.objects.filter(username=username).values_list('id')[0][0]
        return Document.objects.filter(user_id=user_id).order_by('-uploaded_at')[:3]

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        username = self.request.path_info.split('/')[-1]
        like_documents =  CustomUser.objects.filter(username=username).values('like_document')
        
        context['username'] = username
        context['like_documents'] = Document.objects.filter(id__in=like_documents).order_by('-uploaded_at')
        return context
        
class Login(LoginView):
    from_class = LoginForm
    template_name = 'movie/login.html'

class Logout(LogoutView):
    template_name = 'movie/index.html'

class DetailView(generic.DetailView):
    model = Document
    template_name = 'movie/detail.html'
    def get_context_data(self,**kwargs):
        document_id = self.request.path_info.split('/')[-2]
        user = self.request.user
        context = super().get_context_data(**kwargs)
        context['delete'] = str(user)==str(Document.objects.filter(pk=document_id).values_list('username')[0][0])
        follower_id = Document.objects.filter(pk=document_id).values('follower')
        context['follower'] = CustomUser.objects.filter(id__in=follower_id)
        return context

class DeleteView(generic.DeleteView):
    model = Document
    form = DocumentForm

    success_url = reverse_lazy('movie:index')

    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        messages.success(
            self.request, '「{}」を削除しました'.format(self.object))
        return result

@login_required
def add_comment(request, pk):
    post = get_object_or_404(Document, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('movie:detail',pk=pk)
    else:
        form = CommentForm()
    return render(request, 'movie/add_comment.html', {'form': form})
    
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(request,username=username,password=raw_password)
            if user is not None:
                login(request,user)
            return redirect('movie:index')
    else:
        form = SignupForm()
    return render(request, 'movie/signup.html', {'form':form})

@login_required
def model_form_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        form.instance.username = request.user
        form.instance.user = request.user
        if form.is_valid():
            form.save()
            return redirect('movie:index')
    else:
        form = DocumentForm()
    return render(request, 'movie/upload.html', {
        'form': form
    })

@login_required
def edit_profile(request):
    return HttpResponse("You're editing")

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('movie:index')

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('movie:index')

@login_required
def like_document(request, pk):
    document = get_object_or_404(Document, pk=pk)
    if document:
        document.follower.add(request.user)
        request.user.like_document.add(document)
    return redirect('movie:detail',pk=pk)

app/movie/templates/movie/add_comment.html
{% extends 'movie/base.html' %}

{% block content %}
    <h1>New comment</h1>
    <div>ログイン中のユーザー:<a href="{% url 'movie:user' username=request.user %}">{{ request.user }}</a></div>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

app/movie/templates/movie/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>upload prac</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  </head>
  <body>
    <div class="page-header">
      <h1><a href="{% url 'movie:index' %}"}>Image upload site!</a></h1>
        {% if user.is_authenticated %}
            <p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'movie:logout' %}">Log out</a>)</small></p>
            <p class="top-menu"><a href="{% url 'movie:edit_profile' %}">Edit Profile</a></p>
            <h1><a href="{% url 'movie:upload' %}">Upload</a></h1>
        {% else %}
            <a href="{% url 'movie:login' %}" class="top-menu">Login<span class="glyphicon glyphicon-lock"></span></a>
            <a href="{% url 'movie:signup' %}" class="top-menu">Sign Up<span class="glyphicon glyphicon-lock"></span></a>
        {% endif %}
    </div>
    
    <div>
        {% block content %}
        {% endblock %}
    </div>

    
  </body>
</html>

app/movie/templates/movie/detail.html
{% extends 'movie/base.html' %}

{% block content %}
    <h1>Upload Images</h1>

    <img src='{{ MEDIA_URL }}{{ document.document }}' width=200>
    <h2>{{ document.description }}</h2>
    <h3>アップローダー：<a href="{% url 'movie:user' username=document.user %}">{{ document.user }}</h3></a>

    <form action="{% url 'movie:like_document' pk=document.pk %}" method="post">
        <button type="submit" name="button">お気に入り追加</button>
        {% csrf_token %}
    </form>
    <div>favorite:{% for f in follower %}
        <a href="{% url 'movie:user' username=f %}">{{ f }}</a>
    </div>
    {% endfor %}

    <hr>
    <a class="btn btn-default" href="{% url 'movie:add_comment' pk=document.pk %}">Add comment</a>
    {% for comment in document.comments.all %}
        {% if user.is_authenticated or comment.approved_comment %}
            <div class="comment">
                <div class="date">
                    {{ comment.created_date }}
                    {% if not comment.approved_comment  %}
                        <a class="btn btn-default" href="{% url 'movie:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                        <a class="btn btn-default" href="{% url 'movie:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                    {% endif %}
                </div>
                <strong>{{ comment.author }}</strong>
                <p>{{ comment.text|linebreaks }}</p>
            </div>
        {% endif %}
    {% empty %}
        <p>No comments here yet :(</p>
    {% endfor %}
    {% if delete %}
        <div>投稿を削除できます</div>
        <div>
            <a class="btn btn-danger" href="{% url 'movie:remove' document.pk %}">削除</a>
        </div>
    {% endif %}
{% endblock %}

app/movie/templates/movie/document_confirm_delete.html
{% extends 'movie/base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-12">
        <p>{{ object }} を削除していいですか?</p>
        <form method="post">
          <button class="btn btn-danger">削除する</button>
          {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

app/movie/templates/movie/index.html
{% extends 'movie/base.html' %}

{% block content %}
    <form action="" method="get">
        <input name="query" value="{{ request.GET.query }}" type="text">
        <button type="submit">検索する</button>
    </form>
    {% if latest_file_list %}
        <ul>
        
        {% for file in latest_file_list %}
            <li>投稿日：{{ file.uploaded_at }}</li>
            <div><a href="{% url 'movie:detail' file.id %}">
                {{ file.description }}</a>:{{ file.user }}</div>
        {% endfor %}
        </ul>
    {% else %}
        <p>No files are availabel.</p>
    {% endif %}

{% endblock %}

app/movie/templates/movie/login.html
{% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'movie:login' %}">
{% csrf_token %}
    <table>
    <tr>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
    </tr>
    <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
    </tr>
    </table>

    <input type="submit" value="login" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>

app/movie/templates/movie/signup.html
{% extends 'movie/base.html' %}

{% block content %}
  <h2>Default SignUp</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <div>
    <button type="submit">ユーザー登録</button>
    </div>
    <a href="{% url 'movie:index' %}">戻る</a>
  </form>
{% endblock %}

app/movie/templates/movie/upload.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Upload</title>
    </head>
    <body>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">UPload</button>
        </form>
    </body>
</html>

app/movie/templates/movie/user.html
{% extends 'movie/base.html' %}

{% block content %}

    {% if latest_file_list %}
        <ul>
            ユーザー：{{ username }}
        </ul>
        <p>Uploaded files</p>
        <ul>
        {% for file in latest_file_list %}
            <li><a href="{% url 'movie:detail' file.id %}">
                {{ file.description }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No files are availabel.</p>
    {% endif %}

    {% if like_documents %}
        <p>{{ username }}はこの投稿を気に入りました</p>
        <ul>
            {% for like_document in like_documents %}
            <li><a href="{% url 'movie:detail' like_document.id %}">
                {{ like_document.description }}
            </a></li>
            {% endfor %}
        </ul>
        {% else %}
            <p>No favorite files</p>
        {% endif %}

{% endblock %}